import typing
from System import IDisposable
from Autodesk.Revit.DB import Document, Transform, ElementId, Color
from System.Collections.Generic import ICollection_1, IList_1

class AdvancedLossFactor(LossFactor):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, ballastLossFactorIn: float, lampLumenDepreciationIn: float, lampTiltLossFactorIn: float, luminaireDirtDepreciationIn: float, surfaceDepreciationLossFactorIn: float, temperatureLossFactorIn: float, voltageLossFactorIn: float) -> None: ...
    @typing.overload
    def __init__(self, other: AdvancedLossFactor) -> None: ...
    @property
    def BallastLossFactor(self) -> float: ...
    @BallastLossFactor.setter
    def BallastLossFactor(self, value: float) -> float: ...
    @property
    def IsValidObject(self) -> bool: ...
    @property
    def LampLumenDepreciation(self) -> float: ...
    @LampLumenDepreciation.setter
    def LampLumenDepreciation(self, value: float) -> float: ...
    @property
    def LampTiltLossFactor(self) -> float: ...
    @LampTiltLossFactor.setter
    def LampTiltLossFactor(self, value: float) -> float: ...
    @property
    def LossFactorValue(self) -> float: ...
    @property
    def LuminaireDirtDepreciation(self) -> float: ...
    @LuminaireDirtDepreciation.setter
    def LuminaireDirtDepreciation(self, value: float) -> float: ...
    @property
    def SurfaceDepreciationLossFactor(self) -> float: ...
    @SurfaceDepreciationLossFactor.setter
    def SurfaceDepreciationLossFactor(self, value: float) -> float: ...
    @property
    def TemperatureLossFactor(self) -> float: ...
    @TemperatureLossFactor.setter
    def TemperatureLossFactor(self, value: float) -> float: ...
    @property
    def VoltageLossFactor(self) -> float: ...
    @VoltageLossFactor.setter
    def VoltageLossFactor(self, value: float) -> float: ...


class BasicLossFactor(LossFactor):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, lossFactorIn: float) -> None: ...
    @typing.overload
    def __init__(self, other: BasicLossFactor) -> None: ...
    @property
    def IsValidObject(self) -> bool: ...
    @property
    def LossFactor(self) -> float: ...
    @LossFactor.setter
    def LossFactor(self, value: float) -> float: ...
    @property
    def LossFactorValue(self) -> float: ...


class CircleLightShape(LightShape):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, emitDiameter: float) -> None: ...
    @typing.overload
    def __init__(self, other: CircleLightShape) -> None: ...
    @property
    def EmitDiameter(self) -> float: ...
    @EmitDiameter.setter
    def EmitDiameter(self, value: float) -> float: ...
    @property
    def IsValidObject(self) -> bool: ...


class ColorPreset(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    D65 : ColorPreset # 0
    D50 : ColorPreset # 1
    Halogen : ColorPreset # 2
    Incandescent : ColorPreset # 3
    Xenon : ColorPreset # 4
    Quartz : ColorPreset # 5
    FluorescentWarm : ColorPreset # 6
    FluorescentCool : ColorPreset # 7
    FluorescentWhite : ColorPreset # 8
    FluorescentDayLight : ColorPreset # 9
    FluorescentLightWhite : ColorPreset # 10
    MetalHalide : ColorPreset # 11
    HighPressureSodium : ColorPreset # 12
    LowPressureSodium : ColorPreset # 13
    Mercury : ColorPreset # 14
    PhosphorMercury : ColorPreset # 15


class CustomInitialColor(InitialColor):
    @typing.overload
    def __init__(self, other: CustomInitialColor) -> None: ...
    @typing.overload
    def __init__(self, temperature: float) -> None: ...
    @property
    def IsValidObject(self) -> bool: ...
    @property
    def Temperature(self) -> float: ...
    @Temperature.setter
    def Temperature(self, value: float) -> float: ...
    @property
    def TemperatureValue(self) -> float: ...


class HemisphericalLightDistribution(LightDistribution):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, other: HemisphericalLightDistribution) -> None: ...
    @property
    def IsValidObject(self) -> bool: ...


class InitialColor(IDisposable):
    @property
    def IsValidObject(self) -> bool: ...
    @property
    def TemperatureValue(self) -> float: ...
    def Clone(self) -> InitialColor: ...
    def Dispose(self) -> None: ...


class InitialFluxIntensity(InitialIntensity):
    @typing.overload
    def __init__(self, flux: float) -> None: ...
    @typing.overload
    def __init__(self, other: InitialFluxIntensity) -> None: ...
    @property
    def Flux(self) -> float: ...
    @Flux.setter
    def Flux(self, value: float) -> float: ...
    @property
    def InitialIntensityValue(self) -> float: ...
    @property
    def IsValidObject(self) -> bool: ...


class InitialIlluminanceIntensity(InitialIntensity):
    @typing.overload
    def __init__(self, distance: float, illuminance: float) -> None: ...
    @typing.overload
    def __init__(self, other: InitialIlluminanceIntensity) -> None: ...
    @property
    def Distance(self) -> float: ...
    @Distance.setter
    def Distance(self, value: float) -> float: ...
    @property
    def Illuminance(self) -> float: ...
    @Illuminance.setter
    def Illuminance(self, value: float) -> float: ...
    @property
    def InitialIntensityValue(self) -> float: ...
    @property
    def IsValidObject(self) -> bool: ...


class InitialIntensity(IDisposable):
    @property
    def InitialIntensityValue(self) -> float: ...
    @property
    def IsValidObject(self) -> bool: ...
    def Clone(self) -> InitialIntensity: ...
    def Dispose(self) -> None: ...


class InitialLuminousIntensity(InitialIntensity):
    @typing.overload
    def __init__(self, luminosity: float) -> None: ...
    @typing.overload
    def __init__(self, other: InitialLuminousIntensity) -> None: ...
    @property
    def InitialIntensityValue(self) -> float: ...
    @property
    def IsValidObject(self) -> bool: ...
    @property
    def Luminosity(self) -> float: ...
    @Luminosity.setter
    def Luminosity(self, value: float) -> float: ...


class InitialWattageIntensity(InitialIntensity):
    @typing.overload
    def __init__(self, efficacy: float, wattage: float) -> None: ...
    @typing.overload
    def __init__(self, other: InitialWattageIntensity) -> None: ...
    @property
    def Efficacy(self) -> float: ...
    @Efficacy.setter
    def Efficacy(self, value: float) -> float: ...
    @property
    def InitialIntensityValue(self) -> float: ...
    @property
    def IsValidObject(self) -> bool: ...
    @property
    def Wattage(self) -> float: ...
    @Wattage.setter
    def Wattage(self, value: float) -> float: ...


class LightDimmingColor(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : LightDimmingColor # 0
    Incandescent : LightDimmingColor # 1


class LightDistribution(IDisposable):
    @property
    def IsValidObject(self) -> bool: ...
    def Clone(self) -> LightDistribution: ...
    def Dispose(self) -> None: ...


class LightDistributionStyle(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Spherical : LightDistributionStyle # 0
    Hemispherical : LightDistributionStyle # 1
    Spot : LightDistributionStyle # 2
    PhotometricWeb : LightDistributionStyle # 3


class LightFamily(IDisposable):
    @property
    def IsValidObject(self) -> bool: ...
    def Dispose(self) -> None: ...
    def GetLightDistributionStyle(self) -> LightDistributionStyle: ...
    @staticmethod
    def GetLightFamily(document: Document) -> LightFamily: ...
    def GetLightShapeStyle(self) -> LightShapeStyle: ...
    def GetLightSourceTransform(self) -> Transform: ...
    def GetLightType(self, index: int) -> LightType: ...
    def GetLightTypeName(self, index: int) -> str: ...
    def GetNumberOfLightTypes(self) -> int: ...
    def SetLightDistributionStyle(self, lightDistributionStyle: LightDistributionStyle) -> None: ...
    def SetLightShapeStyle(self, lightShapeStyle: LightShapeStyle) -> None: ...


class LightGroup(IDisposable):
    @property
    def Id(self) -> ElementId: ...
    @property
    def IsValidObject(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    def AddLight(self, lightId: ElementId) -> None: ...
    def Dispose(self) -> None: ...
    def GetLights(self) -> ICollection_1[ElementId]: ...
    def RemoveLight(self, lightId: ElementId) -> None: ...


class LightGroupManager(IDisposable):
    @property
    def IsValidObject(self) -> bool: ...
    def CreateGroup(self, name: str) -> LightGroup: ...
    def DeleteGroup(self, groupId: ElementId) -> None: ...
    def Dispose(self) -> None: ...
    def GetGroups(self) -> IList_1[LightGroup]: ...
    def GetLightDimmer(self, viewId: ElementId, lightId: ElementId) -> float: ...
    @staticmethod
    def GetLightGroupManager(document: Document) -> LightGroupManager: ...
    def IsLightGroupOn(self, viewId: ElementId, groupId: ElementId) -> bool: ...
    def IsLightOn(self, viewId: ElementId, lightId: ElementId) -> bool: ...
    def SetLightDimmer(self, viewId: ElementId, lightId: ElementId, dimmingValue: float) -> None: ...
    def SetLightGroupOn(self, viewId: ElementId, groupId: ElementId, turnOn: bool) -> None: ...
    def SetLightOn(self, viewId: ElementId, lightId: ElementId, turnOn: bool) -> None: ...


class LightShape(IDisposable):
    @property
    def IsValidObject(self) -> bool: ...
    def Clone(self) -> LightShape: ...
    def Dispose(self) -> None: ...


class LightShapeStyle(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Point : LightShapeStyle # 0
    Line : LightShapeStyle # 1
    Rectangle : LightShapeStyle # 2
    Circle : LightShapeStyle # 3


class LightType(IDisposable):
    @property
    def ColorFilter(self) -> Color: ...
    @ColorFilter.setter
    def ColorFilter(self, value: Color) -> Color: ...
    @property
    def DimmingColor(self) -> LightDimmingColor: ...
    @DimmingColor.setter
    def DimmingColor(self, value: LightDimmingColor) -> LightDimmingColor: ...
    @property
    def IsValidObject(self) -> bool: ...
    def Dispose(self) -> None: ...
    def GetInitialColor(self) -> InitialColor: ...
    def GetInitialIntensity(self) -> InitialIntensity: ...
    def GetLightDistribution(self) -> LightDistribution: ...
    def GetLightShape(self) -> LightShape: ...
    @staticmethod
    def GetLightType(document: Document, typeId: ElementId) -> LightType: ...
    @staticmethod
    def GetLightTypeFromInstance(document: Document, instanceId: ElementId) -> LightType: ...
    def GetLossFactor(self) -> LossFactor: ...
    def SetInitialColor(self, initialColor: InitialColor) -> None: ...
    def SetInitialIntensity(self, initialIntensity: InitialIntensity) -> None: ...
    def SetLightDistribution(self, lightDistribution: LightDistribution) -> None: ...
    def SetLightShape(self, lightShape: LightShape) -> None: ...
    def SetLossFactor(self, lossFactor: LossFactor) -> None: ...


class LineLightShape(LightShape):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, emitLength: float) -> None: ...
    @typing.overload
    def __init__(self, other: LineLightShape) -> None: ...
    @property
    def EmitLength(self) -> float: ...
    @EmitLength.setter
    def EmitLength(self, value: float) -> float: ...
    @property
    def IsValidObject(self) -> bool: ...


class LossFactor(IDisposable):
    @property
    def IsValidObject(self) -> bool: ...
    @property
    def LossFactorValue(self) -> float: ...
    def Clone(self) -> LossFactor: ...
    def Dispose(self) -> None: ...


class PhotometricWebLightDistribution(LightDistribution):
    @typing.overload
    def __init__(self, other: PhotometricWebLightDistribution) -> None: ...
    @typing.overload
    def __init__(self, photometricWebFile: str, tiltAngle: float) -> None: ...
    @property
    def IsValidObject(self) -> bool: ...
    @property
    def PhotometricWebFile(self) -> str: ...
    @PhotometricWebFile.setter
    def PhotometricWebFile(self, value: str) -> str: ...
    @property
    def TiltAngle(self) -> float: ...
    @TiltAngle.setter
    def TiltAngle(self, value: float) -> float: ...


class PointLightShape(LightShape):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, other: PointLightShape) -> None: ...
    @property
    def IsValidObject(self) -> bool: ...


class PresetInitialColor(InitialColor):
    @typing.overload
    def __init__(self, other: PresetInitialColor) -> None: ...
    @typing.overload
    def __init__(self, presetIn: ColorPreset) -> None: ...
    @property
    def IsValidObject(self) -> bool: ...
    @property
    def Preset(self) -> ColorPreset: ...
    @Preset.setter
    def Preset(self, value: ColorPreset) -> ColorPreset: ...
    @property
    def TemperatureValue(self) -> float: ...


class RectangleLightShape(LightShape):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, emitLength: float, emitWidth: float) -> None: ...
    @typing.overload
    def __init__(self, other: RectangleLightShape) -> None: ...
    @property
    def EmitLength(self) -> float: ...
    @EmitLength.setter
    def EmitLength(self, value: float) -> float: ...
    @property
    def EmitWidth(self) -> float: ...
    @EmitWidth.setter
    def EmitWidth(self, value: float) -> float: ...
    @property
    def IsValidObject(self) -> bool: ...


class SphericalLightDistribution(LightDistribution):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, other: SphericalLightDistribution) -> None: ...
    @property
    def IsValidObject(self) -> bool: ...


class SpotLightDistribution(LightDistribution):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, other: SpotLightDistribution) -> None: ...
    @typing.overload
    def __init__(self, spotBeamAngle: float, spotFieldAngle: float, tiltAngle: float) -> None: ...
    @property
    def IsValidObject(self) -> bool: ...
    @property
    def SpotBeamAngle(self) -> float: ...
    @SpotBeamAngle.setter
    def SpotBeamAngle(self, value: float) -> float: ...
    @property
    def SpotFieldAngle(self) -> float: ...
    @SpotFieldAngle.setter
    def SpotFieldAngle(self, value: float) -> float: ...
    @property
    def TiltAngle(self) -> float: ...
    @TiltAngle.setter
    def TiltAngle(self, value: float) -> float: ...

